export const dataArray = [
  { id: 1, name: "song1", artist: "artist1", album: "album1" },
  { id: 2, name: "song2", artist: "artist2", album: "album2" },
  { id: 3, name: "song3", artist: "artist3", album: "album3" },
  { id: 4, name: "song4", artist: "artist4", album: "album4" },
  { id: 5, name: "song5", artist: "artist5", album: "album5" },
  { id: 6, name: "song6", artist: "artist6", album: "album6" },
  { id: 7, name: "song7", artist: "artist7", album: "album7" },
  { id: 8, name: "song8", artist: "artist8", album: "album8" },
  { id: 9, name: "song9", artist: "artist9", album: "album9" },
  { id: 10, name: "song10", artist: "artist10", album: "album10" },
  { id: 11, name: "song11", artist: "artist11", album: "album11" },
  { id: 12, name: "song12", artist: "artist12", album: "album12" },
  { id: 13, name: "song13", artist: "artist13", album: "album13" },
  { id: 14, name: "song14", artist: "artist14", album: "album14" },
  { id: 15, name: "song15", artist: "artist15", album: "album15" },
  { id: 16, name: "song16", artist: "artist16", album: "album16" },
  { id: 17, name: "song17", artist: "artist17", album: "album17" },
  { id: 18, name: "song18", artist: "artist18", album: "album18" },
  { id: 19, name: "song19", artist: "artist19", album: "album19" },
  { id: 20, name: "song20", artist: "artist20", album: "album20" },
];

export const sideBarData = [
  {
    name: "Home",
    icon: "icon1",
    path: "/",
    cName: "nav-text",
  },
  {
    name: "Register",
    icon: "icon2",
    path: "/register",
    cName: "nav-text",
  },
  {
    name: "Login",
    icon: "icon3",
    path: "/login",
    cName: "nav-text",
  },
  {
    name: "Users",
    icon: "icon4",
    path: "/users",
    cName: "nav-text",
  },
  {
    name: "Search",
    icon: "icon5",
    path: "/search",
    cName: "nav-text",
  },
  {
    name: "Your Library",
    icon: "icon5",
    path: "/music",
    cName: "nav-text",
  },
];
